#ddev-generated

services:
  solr:
    image: solr:9.6
    container_name: ddev-${DDEV_SITENAME}-solr
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr
      SOLR_PORT: 8983
      # The pre-trained OpenNLP models require a much bigger buffer.
      SOLR_OPTS: -Djute.maxbuffer=50000000
      #SOLR_HEAP: 1g
      SOLR_AUTH_TYPE: basic
      SOLR_AUTHENTICATION_OPTS: -Dbasicauth=solr:SolrRocks
      VIRTUAL_HOST: ${DDEV_HOSTNAME}
      HTTP_EXPOSE: 8983:8983
      #HTTPS_EXPOSE: 8943:8983
    volumes:
      - .:/mnt/ddev_config
      - solr:/var/solr
    command: bash -c "
      docker-entrypoint.sh solr start -c;
      solr zk cp file:/mnt/ddev_config/solr/security.json zk:/security.json -z localhost:9983;
      cd /mnt/ddev_config/solr/configsets;
      for dir in */; do
        dir=$${dir%/};
        solr zk upconfig -n \"$$dir\" -d \"$$dir\" -z localhost:9983;
        solr create -c \"$$dir\" -n \"$$dir\" -shards 1 -replicationFactor 1;
      done;
      cd -;
      solr stop;
      exec solr-foreground -c;
      "
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s localhost:8983/solr/"]

  web:
    links:
      - solr:solr

volumes:
  solr:
