#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Run Solr ZooKeeper inside the solr container
## Usage: solr-zk
## Example: "ddev solr-zk"

solr zk -z localhost:9983 "$@"
